"""Utility script to seed the database with baseline recipes."""

from __future__ import annotations

from sqlalchemy import select

from .database import Base, SessionLocal, engine
from .models import Recipe

SAMPLE_RECIPES = [
    {
        "name": "Vegan Butter Tofu",
        "state": "Punjab",
        "course": "Main",
        "diet": "vegan",
        "replaces": ["Butter Chicken", "Chicken Tikka Masala"],
        "flavor_profile": "Rich, creamy, gently spiced",
        "taste_profile": "Sweet, tangy, umami",
        "hero_summary": "Marinated tofu in cashew-tomato makhani gravy",
        "why_it_works": "Tofu absorbs the smoky marinade while cashew cream mirrors butter richness.",
        "ingredients": [
            "firm tofu",
            "cashew cream",
            "tomato puree",
            "vegan butter",
            "garam masala",
            "ginger garlic paste",
            "kasuri methi",
        ],
        "prep_time_minutes": 30,
        "cook_time_minutes": 25,
        "servings": 4,
        "image_url": "/images/vegan-butter-tofu.jpg",
        "texture_match": {
            "original": "Tender chicken in buttery gravy",
            "replacement": "Charred tofu cubes",
            "similarity_score": 0.88,
        },
        "key_substitutions": [
            {
                "original": "chicken",
                "replacement": "firm tofu",
                "type": "protein",
                "reason": "Chewy bite post-marinade",
            },
            {
                "original": "cream",
                "replacement": "cashew cream",
                "type": "dairy",
                "reason": "Same silky body",
            },
        ],
        "nutritional_data": {
            "protein_g": 19,
            "iron_mg": 3.6,
            "b12_mcg": 0,
            "calories": 340,
            "carbs_g": 24,
            "fat_g": 18,
            "fiber_g": 4,
        },
        "cultural_preservation": {
            "cooking_style": "Mughlai",
            "spices_used": ["garam masala", "kasuri methi", "kashmiri chilli"],
            "appearance": "Orange-red glossy gravy",
            "authenticity_score": 0.93,
        },
        "dietary_restrictions": {
            "gluten_free": True,
            "nut_free": False,
            "soy_free": False,
            "onion_free": False,
            "garlic_free": False,
        },
        "transition_difficulty": "easy",
        "emotional_comfort": "high",
        "availability_score": 0.82,
    },
    {
        "name": "Jackfruit Kathi Roll",
        "state": "West Bengal",
        "course": "Snack",
        "diet": "vegan",
        "replaces": ["Chicken Kathi Roll"],
        "flavor_profile": "Smoky, tangy, chutney-laced",
        "taste_profile": "Spicy, savory",
        "hero_summary": "Shredded jackfruit tossed with peppers wrapped in whole wheat paratha",
        "why_it_works": "Fibrous jackfruit mirrors shredded chicken texture and holds marinades well.",
        "ingredients": [
            "young jackfruit",
            "whole wheat paratha",
            "mint chutney",
            "pickled onions",
            "bell peppers",
            "chaat masala",
        ],
        "prep_time_minutes": 25,
        "cook_time_minutes": 15,
        "servings": 4,
        "image_url": "/images/jackfruit-roll.jpg",
        "texture_match": {
            "original": "Shredded chicken",
            "replacement": "Pulled jackfruit",
            "similarity_score": 0.81,
        },
        "key_substitutions": [
            {
                "original": "chicken",
                "replacement": "young jackfruit",
                "type": "protein",
                "reason": "Fibrous strands mimic meat",
            }
        ],
        "nutritional_data": {
            "protein_g": 9,
            "iron_mg": 2.1,
            "b12_mcg": 0,
            "calories": 280,
            "carbs_g": 42,
            "fat_g": 8,
            "fiber_g": 7,
        },
        "cultural_preservation": {
            "cooking_style": "Tawa-griddled",
            "spices_used": ["chaat masala", "kashmiri chilli"],
            "appearance": "Rolled paratha with char marks",
            "authenticity_score": 0.87,
        },
        "dietary_restrictions": {
            "gluten_free": False,
            "nut_free": True,
            "soy_free": True,
            "onion_free": False,
            "garlic_free": False,
        },
        "transition_difficulty": "moderate",
        "emotional_comfort": "medium",
        "availability_score": 0.74,
    },
    {
        "name": "Tempeh Chettinad Curry",
        "state": "Tamil Nadu",
        "course": "Main",
        "diet": "vegan",
        "replaces": ["Chettinad Chicken"],
        "flavor_profile": "Peppery, roasted coconut, curry leaves",
        "taste_profile": "Spicy, earthy",
        "hero_summary": "Tempeh cubes simmered in fiery Chettinad masala",
        "why_it_works": "Tempeh's nutty bite holds up to the roasted spice paste, giving chew similar to poultry.",
        "ingredients": [
            "tempeh",
            "roasted coconut",
            "black pepper",
            "curry leaves",
            "tomato",
            "shallots",
        ],
        "prep_time_minutes": 35,
        "cook_time_minutes": 30,
        "servings": 4,
        "image_url": "/images/tempeh-chettinad.jpg",
        "texture_match": {
            "original": "Bone-in chicken",
            "replacement": "Tempeh cubes",
            "similarity_score": 0.77,
        },
        "key_substitutions": [
            {
                "original": "chicken",
                "replacement": "tempeh",
                "type": "protein",
                "reason": "Firm bite and fermentation depth",
            }
        ],
        "nutritional_data": {
            "protein_g": 21,
            "iron_mg": 4.2,
            "b12_mcg": 0,
            "calories": 360,
            "carbs_g": 20,
            "fat_g": 22,
            "fiber_g": 5,
        },
        "cultural_preservation": {
            "cooking_style": "Chettinad masala",
            "spices_used": ["kalpasi", "anise", "pepper", "coriander"],
            "appearance": "Dark brown masala-coated chunks",
            "authenticity_score": 0.9,
        },
        "dietary_restrictions": {
            "gluten_free": True,
            "nut_free": True,
            "soy_free": False,
            "onion_free": False,
            "garlic_free": False,
        },
        "transition_difficulty": "hard",
        "emotional_comfort": "medium",
        "availability_score": 0.68,
    },
    {
        "name": "Millet Keema Pulao",
        "state": "Maharashtra",
        "course": "Main",
        "diet": "vegetarian",
        "replaces": ["Mutton Keema Pulao"],
        "flavor_profile": "Aromatic, whole garam masala",
        "taste_profile": "Savory, warming",
        "hero_summary": "Foxtail millet with minced soy nuggets and peas",
        "why_it_works": "Crumbled soy mimics minced meat texture while millet provides hearty mouthfeel.",
        "ingredients": [
            "foxtail millet",
            "soy granules",
            "peas",
            "mint",
            "garam masala",
        ],
        "prep_time_minutes": 20,
        "cook_time_minutes": 30,
        "servings": 4,
        "image_url": "/images/millet-keema.jpg",
        "texture_match": {
            "original": "Minced mutton",
            "replacement": "Soy granules",
            "similarity_score": 0.73,
        },
        "key_substitutions": [
            {
                "original": "mutton mince",
                "replacement": "hydrated soy granules",
                "type": "protein",
                "reason": "Granular chew",
            }
        ],
        "nutritional_data": {
            "protein_g": 17,
            "iron_mg": 3.1,
            "b12_mcg": 0,
            "calories": 310,
            "carbs_g": 45,
            "fat_g": 8,
            "fiber_g": 6,
        },
        "cultural_preservation": {
            "cooking_style": "Dum",
            "spices_used": ["bay leaf", "cinnamon", "clove"],
            "appearance": "Speckled grains with herbs",
            "authenticity_score": 0.84,
        },
        "dietary_restrictions": {
            "gluten_free": True,
            "nut_free": True,
            "soy_free": False,
            "onion_free": False,
            "garlic_free": False,
        },
        "transition_difficulty": "moderate",
        "emotional_comfort": "medium",
        "availability_score": 0.71,
    },
    {
        "name": "Plantain Vindaloo",
        "state": "Goa",
        "course": "Main",
        "diet": "vegan",
        "replaces": ["Pork Vindaloo"],
        "flavor_profile": "Vinegary, garlicky, chilli heat",
        "taste_profile": "Tangy, spicy",
        "hero_summary": "Pan-seared plantain coins stewed in vindaloo masala",
        "why_it_works": "Plantains retain bite after simmering and soak tangy masala like pork chunks.",
        "ingredients": [
            "raw plantain",
            "palm vinegar",
            "kashmiri chilli",
            "garlic",
            "cinnamon",
        ],
        "prep_time_minutes": 20,
        "cook_time_minutes": 35,
        "servings": 4,
        "image_url": "/images/plantain-vindaloo.jpg",
        "texture_match": {
            "original": "Pork chunks",
            "replacement": "Golden plantain",
            "similarity_score": 0.69,
        },
        "key_substitutions": [
            {
                "original": "pork",
                "replacement": "plantain",
                "type": "protein",
                "reason": "Firm bite with caramelized edges",
            }
        ],
        "nutritional_data": {
            "protein_g": 6,
            "iron_mg": 2.5,
            "b12_mcg": 0,
            "calories": 290,
            "carbs_g": 52,
            "fat_g": 7,
            "fiber_g": 5,
        },
        "cultural_preservation": {
            "cooking_style": "Catholic Goan",
            "spices_used": ["clove", "cumin", "pepper"],
            "appearance": "Rust-red curry with thick gravy",
            "authenticity_score": 0.8,
        },
        "dietary_restrictions": {
            "gluten_free": True,
            "nut_free": True,
            "soy_free": True,
            "onion_free": False,
            "garlic_free": False,
        },
        "transition_difficulty": "moderate",
        "emotional_comfort": "medium",
        "availability_score": 0.66,
    },
    {
        "name": "Mushroom Pepper Fry",
        "state": "Kerala",
        "course": "Side",
        "diet": "vegan",
        "replaces": ["Pepper Chicken Fry"],
        "flavor_profile": "Pepper-crusted, curry leaf aroma",
        "taste_profile": "Spicy, earthy",
        "hero_summary": "Button mushrooms tossed with crushed pepper and shallots",
        "why_it_works": "Firm mushrooms sear and release umami similar to chicken strips.",
        "ingredients": [
            "button mushroom",
            "black pepper",
            "shallots",
            "curry leaves",
            "coconut oil",
        ],
        "prep_time_minutes": 15,
        "cook_time_minutes": 12,
        "servings": 3,
        "image_url": "/images/mushroom-pepper-fry.jpg",
        "texture_match": {
            "original": "Chicken strips",
            "replacement": "Sliced mushrooms",
            "similarity_score": 0.64,
        },
        "key_substitutions": [
            {
                "original": "chicken",
                "replacement": "mushroom",
                "type": "protein",
                "reason": "Quick-searing bite",
            }
        ],
        "nutritional_data": {
            "protein_g": 8,
            "iron_mg": 1.8,
            "b12_mcg": 0,
            "calories": 190,
            "carbs_g": 12,
            "fat_g": 12,
            "fiber_g": 3,
        },
        "cultural_preservation": {
            "cooking_style": "Toddy shop",
            "spices_used": ["black pepper", "fennel"],
            "appearance": "Dark brown stir fry",
            "authenticity_score": 0.78,
        },
        "dietary_restrictions": {
            "gluten_free": True,
            "nut_free": True,
            "soy_free": True,
            "onion_free": False,
            "garlic_free": False,
        },
        "transition_difficulty": "easy",
        "emotional_comfort": "medium",
        "availability_score": 0.83,
    },
    {
        "name": "Chickpea Cafreal",
        "state": "Goa",
        "course": "Main",
        "diet": "vegan",
        "replaces": ["Chicken Cafreal"],
        "flavor_profile": "Green spice paste, citrus",
        "taste_profile": "Herby, spicy",
        "hero_summary": "Roasted chickpeas coated in cilantro-mint cafreal masala",
        "why_it_works": "Roasted chickpeas stay firm and soak up vibrant marinade similar to roasted chicken.",
        "ingredients": [
            "chickpeas",
            "cilantro",
            "mint",
            "green chilli",
            "lime",
        ],
        "prep_time_minutes": 18,
        "cook_time_minutes": 22,
        "servings": 4,
        "image_url": "/images/chickpea-cafreal.jpg",
        "texture_match": {
            "original": "Roasted chicken",
            "replacement": "Toasted chickpeas",
            "similarity_score": 0.58,
        },
        "key_substitutions": [
            {
                "original": "chicken",
                "replacement": "chickpeas",
                "type": "protein",
                "reason": "Familiar bite when oven-toasted",
            }
        ],
        "nutritional_data": {
            "protein_g": 15,
            "iron_mg": 4.8,
            "b12_mcg": 0,
            "calories": 305,
            "carbs_g": 38,
            "fat_g": 9,
            "fiber_g": 10,
        },
        "cultural_preservation": {
            "cooking_style": "Roasted",
            "spices_used": ["green chilli", "clove", "cinnamon"],
            "appearance": "Green masala-coated legumes",
            "authenticity_score": 0.76,
        },
        "dietary_restrictions": {
            "gluten_free": True,
            "nut_free": True,
            "soy_free": True,
            "onion_free": True,
            "garlic_free": False,
        },
        "transition_difficulty": "easy",
        "emotional_comfort": "medium",
        "availability_score": 0.79,
    },
    {
        "name": "Tofu Tikka Kebabs",
        "state": "Punjab",
        "course": "Starter",
        "diet": "vegan",
        "replaces": ["Chicken Tikka"],
        "flavor_profile": "Smoky tandoor spices",
        "taste_profile": "Tangy, spicy",
        "hero_summary": "Tofu cubes skewered with peppers and onions in hung-curd style marinade",
        "why_it_works": "Hung vegan yogurt and besan marinade yields charred crust like chicken tikka.",
        "ingredients": [
            "firm tofu",
            "vegan yogurt",
            "gram flour",
            "bell peppers",
            "kasuri methi",
            "lemon",
        ],
        "prep_time_minutes": 40,
        "cook_time_minutes": 15,
        "servings": 4,
        "image_url": "/images/tofu-tikka.jpg",
        "texture_match": {
            "original": "Tandoori chicken",
            "replacement": "Tofu skewers",
            "similarity_score": 0.82,
        },
        "key_substitutions": [
            {
                "original": "chicken",
                "replacement": "firm tofu",
                "type": "protein",
                "reason": "Holds grill marks",
            }
        ],
        "nutritional_data": {
            "protein_g": 20,
            "iron_mg": 3.2,
            "b12_mcg": 0,
            "calories": 260,
            "carbs_g": 16,
            "fat_g": 14,
            "fiber_g": 3,
        },
        "cultural_preservation": {
            "cooking_style": "Tandoor",
            "spices_used": ["garam masala", "cumin", "paprika"],
            "appearance": "Charred orange skewers",
            "authenticity_score": 0.89,
        },
        "dietary_restrictions": {
            "gluten_free": True,
            "nut_free": True,
            "soy_free": False,
            "onion_free": False,
            "garlic_free": False,
        },
        "transition_difficulty": "easy",
        "emotional_comfort": "high",
        "availability_score": 0.86,
    },
    {
        "name": "Soy-Free Malai Kofta",
        "state": "Delhi",
        "course": "Main",
        "diet": "vegetarian",
        "replaces": ["Malai Kofta"],
        "flavor_profile": "Creamy, cashew-based",
        "taste_profile": "Sweet, savory",
        "hero_summary": "Bottle gourd and potato kofta in coconut-cashew gravy",
        "why_it_works": "Kofta provide soft bite similar to paneer dumplings without soy or nuts.",
        "ingredients": [
            "bottle gourd",
            "potato",
            "coconut cream",
            "cashew",
            "raisins",
            "cumin",
        ],
        "prep_time_minutes": 35,
        "cook_time_minutes": 25,
        "servings": 4,
        "image_url": "/images/soy-free-malai-kofta.jpg",
        "texture_match": {
            "original": "Paneer kofta",
            "replacement": "Bottle gourd kofta",
            "similarity_score": 0.7,
        },
        "key_substitutions": [
            {
                "original": "paneer",
                "replacement": "grated bottle gourd",
                "type": "protein",
                "reason": "Soft airy dumpling",
            }
        ],
        "nutritional_data": {
            "protein_g": 11,
            "iron_mg": 2.7,
            "b12_mcg": 0,
            "calories": 330,
            "carbs_g": 28,
            "fat_g": 20,
            "fiber_g": 4,
        },
        "cultural_preservation": {
            "cooking_style": "North Indian",
            "spices_used": ["elaichi", "cinnamon"],
            "appearance": "Creamy off-white gravy",
            "authenticity_score": 0.75,
        },
        "dietary_restrictions": {
            "gluten_free": True,
            "nut_free": False,
            "soy_free": True,
            "onion_free": False,
            "garlic_free": False,
        },
        "transition_difficulty": "moderate",
        "emotional_comfort": "medium",
        "availability_score": 0.7,
    },
    {
        "name": "Sprouted Lentil Seekh",
        "state": "Uttar Pradesh",
        "course": "Starter",
        "diet": "vegan",
        "replaces": ["Mutton Seekh Kebab"],
        "flavor_profile": "Smoky, charred, spice-loaded",
        "taste_profile": "Savory, umami",
        "hero_summary": "Sprouted lentils and mushrooms minced and grilled on skewers",
        "why_it_works": "Sprouts offer bite while mushrooms lend meaty chew and moisture for skewers.",
        "ingredients": [
            "sprouted moong",
            "portobello",
            "onion",
            "ginger",
            "garam masala",
            "mustard oil",
        ],
        "prep_time_minutes": 45,
        "cook_time_minutes": 20,
        "servings": 4,
        "image_url": "/images/lentil-seekh.jpg",
        "texture_match": {
            "original": "Minced mutton seekh",
            "replacement": "Sprout-mushroom mince",
            "similarity_score": 0.74,
        },
        "key_substitutions": [
            {
                "original": "mutton mince",
                "replacement": "sprouted lentils",
                "type": "protein",
                "reason": "Grind binds around skewers",
            }
        ],
        "nutritional_data": {
            "protein_g": 18,
            "iron_mg": 3.9,
            "b12_mcg": 0,
            "calories": 250,
            "carbs_g": 26,
            "fat_g": 8,
            "fiber_g": 8,
        },
        "cultural_preservation": {
            "cooking_style": "Grilled",
            "spices_used": ["garam masala", "jeera", "chilli"],
            "appearance": "Charred cylindrical seekh",
            "authenticity_score": 0.82,
        },
        "dietary_restrictions": {
            "gluten_free": True,
            "nut_free": True,
            "soy_free": True,
            "onion_free": False,
            "garlic_free": False,
        },
        "transition_difficulty": "hard",
        "emotional_comfort": "medium",
        "availability_score": 0.65,
    },
]


def seed() -> None:
    """Populate the database with curated recipes if they do not exist."""

    Base.metadata.create_all(bind=engine)
    session = SessionLocal()
    try:
        for payload in SAMPLE_RECIPES:
            exists = session.execute(
                select(Recipe).where(Recipe.name == payload["name"])
            ).scalar_one_or_none()
            if exists:
                continue
            recipe = Recipe(**payload)
            session.add(recipe)
        session.commit()
    finally:
        session.close()


if __name__ == "__main__":
    seed()
